# Docker image.
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

name: $(SourceBranchName)
pool:
  vmImage: 'Ubuntu-16.04'
variables:
- group: Settings

stages:
- stage: Build
  displayName: Build

  jobs:
  - job: GetVersion
    displayName: Get Version
    variables:
      repo: $(Build.Repository.Name)
    steps:
    - bash: |
        VERSIONT=$(jq -r .version package.json)
        echo "##vso[task.setvariable variable=version;isOutput=true]$VERSIONT"
        REPOT=$(echo ${repo##*/})
        echo "##vso[task.setvariable variable=webApp;isOutput=true]$REPOT"
      name: App 
  - job: Build
    displayName: Build 
    dependsOn: GetVersion
    variables:
      appVersion: $[ dependencies.GetVersion.outputs['App.version'] ]
      buildIncrement: $[counter(variables['appVersion'], 0)] # create a counter that is used to increment build run for same app version
      buildRevision: "r$(buildIncrement)"
      buildVersion: "$(appVersion)"

- stage: "test" 
  jobs:
  - job: A
    steps:
    - bash: echo "Hello From A o $(System.StageName) the definition is $(System.DefinitionId) in $(System.TeamProjectId)	"

  - job: B
    steps:
    - task: PowerShell@2
      env: 
        token: $(token)
        buildid : $(Build.BuildId)
        dir: $(System.DefaultWorkingDirectory)
        stage: $(System.StageName)
        projectid: $(System.TeamProjectId)
        versionid: v$(Build.BuildNumber)
        webappName: $(Build.DefinitionName)
      inputs:
        filePath: 'Hook.ps1'



      

    
