
pool:
  vmImage: 'Ubuntu-16.04'

trigger:
- master
- develop

resources:
  repositories:
  - repository: RepoB
    type: github
    name: zahidferz/RepoB
    endpoint: zahidferz
    ref: master
    trigger:
    - master
    - develop
 
  - repository: RepoC
    type: github
    name: zahidferz/RepoC
    endpoint: zahidferz
    ref: master
    trigger:
    - master
    - develop

stages:
- stage: dev
  displayName: dev

  jobs:
  - job: Initial
    displayName: Initial
    steps:
    
    - bash: echo "new commit"