
name: $(SourceBranchName)
pool:
  vmImage: 'Ubuntu-16.04'

trigger:
- master
- develop


resources:    
  pipelines:
  - pipeline: RepoB   # Name of the pipeline resource
    source: RepoB # Name of the pipeline referenced by the pipeline resource
    trigger: 
      branches:
      - develop
      - staging
      - master
 
stages:
- stage: build
  displayName: build

  jobs:

  - job: triggering
    displayName: triggering
    steps:
    - checkout: none
    - bash: |
        echo "Trigger from repo $(Build.Repository.Uri) on branch $(Build.SourceBranchName). \n Go to the Repos project: \n https://dev.azure.com/eleva-inc/ERR/_build?definitionId=186"
      name: App 