# Docker image.
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

name: Test
pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: Settings

stages:
- stage: "dev" 
  jobs:
  - job: A
    steps:
    - bash: echo "Hello From A o dev"

  - job: B
    steps:
    - bash: echo "Hello From B on dev"

- stage: "test" 
  jobs:
  - job: A
    steps:
    - bash: echo "Hello From A o test the definition is $(System.DefinitionId)"

  - job: B
    steps:
    - bash: echo "Hello From B on $(System.StageName)"

  - job: C
    steps:
    - task: PowerShell@2
      inputs:
        filePath: 'Hook.ps1'
        arguments: 'id $(System.DefinitionId)'

    
