
trigger:
- master
- develop

resources:    
  pipelines:
  - pipeline: RepoB   # Name of the pipeline resource
    source: RepoB # Name of the pipeline referenced by the pipeline resource
    trigger: 
      branches:
      - develop
      - staging
      - master
 

