
trigger:
- master
- develop

resources:
  repositories:
  - repository: RepoB
    type: github
    name: zahidferz/RepoB
    ref: master
    trigger:
    - master
    - develop
 
  - repository: RepoC
    type: github
    name: zahidferz/RepoC
    ref: master
    trigger:
    - master
    - develop
